config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :lessons do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:index, :update] do
    get "/accept", to: "bookings#accept"
    get "/reject", to: "bookings#reject"
  end
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  STATUS = ["accepted", "rejected", "pending"]
  belongs_to :user
  belongs_to :lesson
  validates :total_price, presence: true, numericality: true
  validates :duration_min, presence: true, numericality: { only_integer: true }
  validates :teaching_date, presence: true
  validates :status, inclusion: {in: STATUS}
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  has_many :bookings
  validates :hourly_prices, presence: true, numericality: true
  validates :coding_language, :description, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :booking
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :comment, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  has_many :lessons
  has_many :bookings
  has_many :teacher_bookings, through: :lessons, source: :bookings
  has_many :reviews

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :first_name, :last_name, :phone, :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    # return a collection with all bookings
    # booking -> lesson -> user
    @bookings = Booking.joins(:lesson).where(lesson: { user: current_user })
    @student_bookings = Booking.where(user: current_user)
  end

  def accept
    @booking = Booking.find(params["booking_id"])
    if @booking.update(status: "accepted")
      flash[:alert] = "Booking Accepted"
      redirect_to bookings_path
    else
      flash[:alert] = "Error, try again"
      redirect_to bookings_path
    end
  end

  def reject
    @booking = Booking.find(params["booking_id"])
    if @booking.update(status: "rejected")
      flash[:alert] = "Sorry, Booking Rejected"
      redirect_to bookings_path
    else
      flash[:alert] = "Error, try again"
      redirect_to bookings_path
    end
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.lesson_id = params[:lesson_id]
    @booking.total_price = (@booking.duration_min.to_f / 60) * @booking.lesson.hourly_prices
    @lesson = Lesson.find(params[:lesson_id])
    @rating_average = 4
    if @booking.save
      flash[:alert] = "Booking created, waiting for teacher validation!"
      redirect_to root_path
    else
      flash[:alert] = "Booking error, please try again!"
      render "lessons/show"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:total_price, :duration_min, :teaching_date, :user_id, :lesson_id, :comment, :total_price)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    if params[:code_language].present? && Lesson.where(coding_language: params[:code_language]).count != 0
        @lessons = Lesson.where(coding_language: params[:code_language])
    # elsif @lessons.count == 0
    #       @lessons = Lesson.all
    else
      @lessons = Lesson.all
    end

    @users = User.where(id: @lessons.pluck(:user_id))
    # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    @markers = @users.geocoded.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        info_window: render_to_string(partial: "info_window", locals: { user: user }),
        image_url: helpers.asset_url(user.lessons.first.language_image)
      }
    end
  end

  def show
    @lesson = Lesson.find(params[:id])
    @booking = Booking.new
    @rating_average = 4
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
<div class="container-bookings">
<% if user_signed_in? %>
  <div>
    <%= cl_image_tag current_user.photo.key, width: 56, height: 56, class: "avatar-large" %>
    <h1> <%= current_user.first_name %> </h1>
  </div>

  <div class="d-flex justify-content-between">
    <div class="bookings-card flex-grow-1">
      <% @bookings.each do |booking| %>
        <div class="box-container">
            <div class="box-left">
              <%= cl_image_tag booking.user.photo.key, width: 56, height: 56, class: "avatar-large" %>
            </div>
            <div class="box-center">
              <h1>Student Information</h1>
                <p>Name: <%= booking.user.first_name %> <%= booking.user.last_name %></p>
                <p>Lesson: <%= booking.lesson.coding_language %></p>
                <p>Email: <%= booking.user.email %></p>
                <p>Phone: <%= booking.user.phone %></p>
                <p>Address: <%= booking.user.address %></p>
                <p>Teaching Price: <%= booking.total_price %>€</p>
                <p>Comment: <%= booking.comment %></p>
            </div>


          <div class="box-right">
            <p>Date: <%= booking.teaching_date.strftime("%-d %B %Y") %></p>
            <% if booking.status == "pending" %>
              <%= link_to "Accept", booking_accept_path(booking), class: "btn btn-success" %>
              <%= link_to "Reject", booking_reject_path(booking), class: "btn btn-danger" %>
              <% elsif booking.status == "accepted" %>
              <p>Accepted</p>
              <% else %>
              <p>Rejected</p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <% else %>
    <h1>There is nothing to see here</h1>
  <% end %>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coco</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/lessons/_info_window.html.erb
<div>
  <%= cl_image_tag user.photo.key, width: 56, height: 56, class: "avatar-large" %>
  <h2><%= user.first_name %></h2>
  <% lesson = Lesson.find_by(user_id: user.id) %>
  <%= image_tag "#{lesson.coding_language}.png", width: 40 %>
  <p><%= user.address %></p>
  <p><%= "#{lesson.hourly_prices} €/h" %></p>
</div>

app/views/lessons/index.html.erb
<div class="main-container">
  <div class="second-container">
    <% @lessons.each do |lesson| %>
        <div class="card-container">
          <div class="cc-left">
            <%#= cl_image_tag(lesson.user.photo.key, height: 100, width: 100, crop: :fill, class: "avatar-large") %>
            <%= cl_image_tag lesson.user.photo.key, width: 56, height: 56, class: "avatar-large" %>
            <p>★★★★★</p>
            <%= image_tag "#{lesson.coding_language}.png", width: 40 %>
            <%= link_to "Book", lesson_path(lesson.id), class: "btn btn-primary mt-3" %>
          </div>
          <div class="cc-right">
            <h2><%= lesson.user.first_name %> </h2>
            <p><%= truncate(lesson.description, :length => 300) %></p>
            <p id="price"><%= lesson.hourly_prices %> €/h</p>
          </div>
        </div>
    <% end %>
  </div>

  <div id="map" style="width: 100%; height: 100vh;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/lessons/show.html.erb
<div class="container-main">
  <div class="card-container2">
    <div class="container-up">
      <div class="container-up-left">
            <%= cl_image_tag(@lesson.user.photo.key, crop: :fill, class: "avatar-extra-large") %>
      </div>
      <div class="container-up-right">
        <h1><%= @lesson.user.first_name %></h1>
        <% @rating_average.times do %>
          ★
        <% end %>
        <% (5 - @rating_average).times do %>
          ☆
        <% end %>
        <div class="coding-logo">
          <% if @lesson.coding_language == "html5" %>
          <%= image_tag "html5.png", alt: "css", width: 50 %>
          <% elsif @lesson.coding_language == "ruby" %>
          <%= image_tag "ruby.png", alt: "css", width: 50 %>
          <% elsif @lesson.coding_language == "css3" %>
          <%= image_tag "css3.png", alt: "css", width: 50 %>
          <% elsif @lesson.coding_language == "python" %>
          <%= image_tag "python.png", alt: "css", width: 50 %>
          <% elsif @lesson.coding_language == "javascript" %>
          <%= image_tag "javascript.png", alt: "css", width: 50 %>
          <% elsif @lesson.coding_language == "sql" %>
          <%= image_tag "sql.png", alt: "css", width: 50 %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="container-down">
      <div class="description">
        <p><b><%= @lesson.user.first_name %></b> <%= @lesson.description %></p>
      </div>
      <div class="adresse-container">
        <div class="adresse-container-left">
          <%= image_tag "pin_ruby.png", alt: "Ruby pin" %>
        </div>
         <div class="adresse-container-right">
          <b>location:</b>
          <%= @lesson.user.address %>
        </div>
      </div>
      <p class="price"><b><%= @lesson.hourly_prices %> €/h</b></p>
    </div>
  </div>
  <div class="form-container" data-controller="total-price">
      <%= simple_form_for [ @lesson, @booking ] do |f| %>
      <%= f.input :teaching_date, as: :date, html5: true %>
      <%= f.input :comment, as: :text %>
      <%= f.input :duration_min, as: :radio_buttons, collection: [['60', '60 min'], ['90', '90 min'], ['120', '120 min']], label_method: :second, value_method: :first, :checked => ['60', '60 min'], input_html: { data: { action: 'click->total-price#calculate' }}  %>
      <p class="d-none" data-total-price-target="hourlyPrice"><%= @lesson.hourly_prices %></p>
      <p data-total-price-target="totalPrice">Total price: <%= @lesson.hourly_prices %>€</p>
      <% @booking.total_price = @lesson.hourly_prices * (@booking.duration_min.to_f / 60) %>
       <%= f.input :total_price, as: :hidden, input_html: { value: @booking.total_price } %>
      <%= f.submit "Book", class: "btn btn-primary" %>
  <% end %>
  </div>
  <div class="form-reviews">
    <h1>Reviews</h1>
    <p>No reviews yet!</p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "background.jpg" %>);">
  <div class="container">
    <div>
      <h1>Find your <strong>Co</strong>ding <strong>Co</strong>ach</h1>
      <p>Book a coach to help you learn to code!</p>
    </div>
    <%= link_to "Look for your coach", lessons_path, class:"btn-rounded" %>
  </div>
  <div class="cards-language">
    <%= link_to lessons_path(code_language: "ruby") do %><%= image_tag "ruby.png", class: "card-language" %><% end %>
    <%= link_to lessons_path(code_language: "javascript") do %><%= image_tag "javascript.png", class: "card-language" %><% end %>
    <%= link_to lessons_path(code_language: "python") do %><%= image_tag "python.png", class: "card-language" %><% end %>
    <%= link_to lessons_path(code_language: "css3") do %><%= image_tag "css3.png", class: "card-language" %><% end %>
    <%= link_to lessons_path(code_language: "html5") do %><%= image_tag "html5.png", class: "card-language" %><% end %>
    <%= link_to lessons_path(code_language: "sql") do %><%= image_tag "sql.png", class: "card-language" %><% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= 'navbar-home' if action_name == 'home' %>">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "coco_logo.png", width: 100 %>
      <span>
        <% if user_signed_in? %>
          Hi <%= current_user.first_name %> !
        <% end %>
      </span>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>